### ISSUE TITLE
Java Client API that does not use Google's gson, swagger, and okhttp libraries

### ISSUE THREAD

**Issue by oliverhernando** [CyberSource/cybersource-rest-client-java#45]
Hi Cybersource Team,

My team is currently doing integration with your REST Payments API and the Flex Microform.
We are using this "cybersource-rest-client-java" API of yours and so far so good. However, we are considering other means because we don't want to have dependencies on Google's gson, swagger, and okhttp libraries. Is there any available Java REST client that perhaps uses Jersey and Jackson?
I've been searching in here but could not find any. 
Here are the relevant end points we are using.

https://apitest.cybersource.com/flex/v1/keys
https://apitest.cybersource.com/pts/v2/payments

Thank you.
Oliver

**Comment by brianmc** [comment]
Hi Oliver, that's good feedback and we're always trying to reduce dependencies in the SDK while balancing that with maintenance efficiencies, so that we can keep them up to date easily and in a timely fashion.  This is the official, supported  CyberSource SDK so we do not have another one however you could look at perhaps forking this and seeing what a flexible/pluggable parser framework would look like (bring your own Jackson/Jersey/gson/etc).  We might even be able to collaborate on incorporating that into the main project (no promises there but we're open to contributions).

**Comment by sporniket** [comment]
I have the same problem toward the coupling of the api model (data models, interfaces, signature computations) and the various commodity frameworks that have been chosen to implement the actual call. Usually I don't mind, except that integrating this library has a side effect on the Tomcat cache background process management that complains continuously.

I understand the need to maintain only one implementation for efficiency, and I believe that being able to separate the api model from commodities would be a good compromise. 

I understand the preferred way to propose a contribution, I may propose something if I devise something suitable.
